# [TODO] - remove this line, once we are ready to use openshift-installer from the release
FROM quay.io/yshnaidm/openshift-installer


FROM fedora:31
RUN dnf install -y libvirt-libs pip python && \
   yum clean all && \
   rm -rf /var/cache/yum


RUN pip install boto3
RUN pip install botocore

ARG WORK_DIR=/data

RUN mkdir $WORK_DIR
RUN chmod 777 $WORK_DIR

# [TODO] - change this line to use openshift-installer from the release, once we are ready
COPY --from=0 /root/installer/openshift-install $WORK_DIR
COPY ./render_files.py $WORK_DIR

ENV WORK_DIR=$WORK_DIR

ENV EXEC_PATH=$WORK_DIR/render_files.py
ENTRYPOINT python $EXEC_PATH