#FROM python:2.7
FROM fedora:31
RUN dnf install -y libvirt-libs pip python && \
   yum clean all && \
   rm -rf /var/cache/yum


RUN pip install boto3
RUN pip install botocore

ARG WORK_DIR=/data

RUN mkdir $WORK_DIR
RUN chmod 777 $WORK_DIR

COPY ./openshift-install $WORK_DIR
COPY ./process-ignition-manifests-and-kubeconfig.py $WORK_DIR

ENV WORK_DIR=$WORK_DIR

ENV EXEC_PATH=$WORK_DIR/process-ignition-manifests-and-kubeconfig.py
ENTRYPOINT python $EXEC_PATH
