#FROM python:2.7
FROM fedora:31
RUN dnf install -y libvirt-libs pip python && \
   yum clean all && \
   rm -rf /var/cache/yum


RUN pip install boto3
RUN pip install botocore

COPY ./openshift-install /
COPY ./process-ignition-manifests-and-kubeconfig.py /

ENTRYPOINT ["python", "process-ignition-manifests-and-kubeconfig.py"]
