# [TODO] - remove this line, once we are ready to use openshift-installer from the release
FROM quay.io/ocpmetal/openshift-installer
# [TODO] - add someway to get oc client in order to use it to extract openshift-baremetal-install executable
# FROM quay.io/yshnaidm/oc-image:latest
FROM quay.io/ocpmetal/bm-inventory:latest AS inventory


FROM centos:8
RUN dnf install -y libvirt-libs python3 findutils && \
   yum clean all && \
   rm -rf /var/cache/yum


COPY requirements.txt /tmp/requirements.txt
COPY --from=inventory /clients/bm-inventory-client-*.tar.gz /build/pip/
RUN pip3 install -r /tmp/requirements.txt
RUN pip3 install ipython
RUN find /build/pip/ -name 'setup.py' -exec dirname {} \; | xargs pip3 install

RUN rm /tmp/*requirements.txt

ARG WORK_DIR=/data

RUN mkdir $WORK_DIR
RUN chmod 777 $WORK_DIR

RUN mkdir /root/.docker

# [TODO] - change this line to use openshift-installer from the release, once we are ready
COPY --from=0 /root/installer/openshift-install $WORK_DIR
#COPY --from=0 /root/oc/oc $WORK_DIR
COPY ./render_files.py $WORK_DIR
COPY ./utils.py $WORK_DIR
COPY ./test_utils.py $WORK_DIR

ENV WORK_DIR=$WORK_DIR

ENV EXEC_PATH=$WORK_DIR/render_files.py
ENTRYPOINT python3 $EXEC_PATH
